In [1]:
import mysql.connector
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
import os
from dotenv import load_dotenv
import unicodedata
import re
import pickle

In [2]:
pd.set_option("display.max_columns", None)

Load data from MySQL

In [3]:
load_dotenv()

# Event data
conn = mysql.connector.connect(
    host=os.getenv("DB_HOST"),
    user=os.getenv("DB_USER"),
    database=os.getenv("DB_NAME"),
    password=os.getenv("DB_PASSWORD")
    )

cursor = conn.cursor()

query = ("SELECT * FROM events")

cursor.execute(query)

columns = [desc[0] for desc in cursor.description]

rows = cursor.fetchall()

df_events = pd.DataFrame(rows, columns=columns)

cursor.close()
conn.close()

Preview dataset

In [4]:
df_events.tail()

,id,event_date,event_name,fighter_red,fighter_blue,round,time,weight_class,win_method,winner,stance_red,stance_blue,knockdowns_red,knockdowns_blue,sig_attempts_red,sig_attempts_blue,sig_strikes_red,sig_strikes_blue,total_strikes_attempts_red,total_strikes_attempts_blue,total_strikes_red,total_strikes_blue,sub_attempts_red,sub_attempts_blue,takedowns_red,takedowns_blue,takedown_attempts_red,takedown_attempts_blue,control_time_red,control_time_blue,head_strikes_red,head_strikes_blue,head_attempts_red,head_attempts_blue,body_strikes_red,body_strikes_blue,body_attempts_red,body_attempts_blue,leg_strikes_red,leg_strikes_blue,leg_attempts_red,leg_attempts_blue,distance_red,distance_blue,distance_attempts_red,distance_attempts_blue,clinch_strikes_red,clinch_strikes_blue,clinch_attempts_red,clinch_attempts_blue,ground_strikes_red,ground_strikes_blue,ground_attempts_red,ground_attempts_blue
8500,8501,2026-01-24,UFC 324: Gaethje vs. Pimblett,Natalia Silva,Rose Namajunas,3,300,Women's Flyweight,Decision - Unanimous,Natalia Silva,Southpaw,Orthodox,0.0,0.0,133.0,94.0,51.0,26.0,147.0,119.0,63.0,46.0,0.0,0.0,1.0,1.0,2.0,5.0,84,129,25.0,11.0,95.0,64.0,8.0,3.0,14.0,13.0,18.0,12.0,24.0,17.0,50.0,26.0,132.0,92.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0
8501,8502,2026-01-24,UFC 324: Gaethje vs. Pimblett,Justin Gaethje,Paddy Pimblett,5,300,UFC Interim Lightweight Title,Decision - Unanimous,Justin Gaethje,Orthodox,Orthodox,2.0,0.0,254.0,311.0,144.0,156.0,313.0,326.0,200.0,170.0,0.0,0.0,3.0,0.0,3.0,5.0,355,48,120.0,83.0,222.0,221.0,15.0,48.0,21.0,63.0,9.0,25.0,11.0,27.0,102.0,140.0,198.0,284.0,20.0,16.0,27.0,27.0,22.0,0.0,29.0,0.0
8502,8503,2026-01-24,UFC 324: Gaethje vs. Pimblett,Waldo Cortes Acosta,Derrick Lewis,2,194,Heavyweight,KO/TKO,Waldo Cortes Acosta,Orthodox,Orthodox,1.0,0.0,62.0,43.0,44.0,8.0,64.0,43.0,46.0,8.0,0.0,0.0,1.0,0.0,1.0,0.0,28,0,35.0,6.0,53.0,37.0,5.0,2.0,5.0,5.0,4.0,0.0,4.0,1.0,27.0,8.0,45.0,43.0,1.0,0.0,1.0,0.0,16.0,0.0,16.0,0.0
8503,8504,2026-01-24,UFC 324: Gaethje vs. Pimblett,Alex Perez,Charles Johnson,1,196,Flyweight,KO/TKO,Alex Perez,Orthodox,Switch,2.0,0.0,75.0,25.0,39.0,8.0,94.0,25.0,55.0,8.0,0.0,0.0,0.0,0.0,0.0,1.0,14,0,27.0,4.0,60.0,14.0,9.0,3.0,10.0,9.0,3.0,1.0,5.0,2.0,33.0,8.0,67.0,25.0,4.0,0.0,6.0,0.0,2.0,0.0,2.0,0.0
8504,8505,2026-01-24,UFC 324: Gaethje vs. Pimblett,Adam Fugitt,Ty Miller,1,299,Welterweight,KO/TKO,Ty Miller,Southpaw,Orthodox,0.0,1.0,73.0,121.0,36.0,59.0,76.0,129.0,39.0,65.0,0.0,0.0,0.0,0.0,2.0,0.0,0,3,10.0,55.0,42.0,115.0,21.0,4.0,26.0,6.0,5.0,0.0,5.0,0.0,30.0,55.0,67.0,115.0,6.0,3.0,6.0,4.0,0.0,1.0,0.0,2.0

In [5]:
df_events.info()

<class 'pandas.DataFrame'>
RangeIndex: 8505 entries, 0 to 8504
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           8505 non-null   int64
 1   event_date                   8505 non-null   object
 2   event_name                   8505 non-null   str
 3   fighter_red                  8484 non-null   str
 4   fighter_blue                 8484 non-null   str
 5   round                        8505 non-null   int64
 6   time                         8505 non-null   int64
 7   weight_class                 8505 non-null   str
 8   win_method                   8505 non-null   str
 9   winner                       8354 non-null   str
 10  stance_red                   8463 non-null   str
 11  stance_blue                  8426 non-null   str
 12  knockdowns_red               8484 non-null   float64
 13  knockdowns_blue              8484 non-null   float64
 14  sig_attempts_red             8484 non-null   float64
 15  sig_attempts_blue            8484 non-null   float64
 16  sig_strikes_red              8484 non-null   float64
 17  sig_strikes_blue             8484 non-null   float64
 18  total_strikes_attempts_red   8484 non-null   float64
 19  total_strikes_attempts_blue  8484 non-null   float64
 20  total_strikes_red            8484 non-null   float64
 21  total_strikes_blue           8484 non-null   float64
 22  sub_attempts_red             8484 non-null   float64
 23  sub_attempts_blue            8484 non-null   float64
 24  takedowns_red                8484 non-null   float64
 25  takedowns_blue               8484 non-null   float64
 26  takedown_attempts_red        8484 non-null   float64
 27  takedown_attempts_blue       8484 non-null   float64
 28  control_time_red             8505 non-null   int64
 29  control_time_blue            8505 non-null   int64
 30  head_strikes_red             8484 non-null   float64
 31  head_strikes_blue            8484 non-null   float64
 32  head_attempts_red            8484 non-null   float64
 33  head_attempts_blue           8484 non-null   float64
 34  body_strikes_red             8484 non-null   float64
 35  body_strikes_blue            8484 non-null   float64
 36  body_attempts_red            8484 non-null   float64
 37  body_attempts_blue           8484 non-null   float64
 38  leg_strikes_red              8484 non-null   float64
 39  leg_strikes_blue             8484 non-null   float64
 40  leg_attempts_red             8484 non-null   float64
 41  leg_attempts_blue            8484 non-null   float64
 42  distance_red                 8484 non-null   float64
 43  distance_blue                8484 non-null   float64
 44  distance_attempts_red        8484 non-null   float64
 45  distance_attempts_blue       8484 non-null   float64
 46  clinch_strikes_red           8484 non-null   float64
 47  clinch_strikes_blue          8484 non-null   float64
 48  clinch_attempts_red          8484 non-null   float64
 49  clinch_attempts_blue         8484 non-null   float64
 50  ground_strikes_red           8484 non-null   float64
 51  ground_strikes_blue          8484 non-null   float64
 52  ground_attempts_red          8484 non-null   float64
 53  ground_attempts_blue         8484 non-null   float64
dtypes: float64(40), int64(5), object(1), str(8)
memory usage: 3.5+ MB

In [6]:
df_events.describe()

,id,round,time,knockdowns_red,knockdowns_blue,sig_attempts_red,sig_attempts_blue,sig_strikes_red,sig_strikes_blue,total_strikes_attempts_red,total_strikes_attempts_blue,total_strikes_red,total_strikes_blue,sub_attempts_red,sub_attempts_blue,takedowns_red,takedowns_blue,takedown_attempts_red,takedown_attempts_blue,control_time_red,control_time_blue,head_strikes_red,head_strikes_blue,head_attempts_red,head_attempts_blue,body_strikes_red,body_strikes_blue,body_attempts_red,body_attempts_blue,leg_strikes_red,leg_strikes_blue,leg_attempts_red,leg_attempts_blue,distance_red,distance_blue,distance_attempts_red,distance_attempts_blue,clinch_strikes_red,clinch_strikes_blue,clinch_attempts_red,clinch_attempts_blue,ground_strikes_red,ground_strikes_blue,ground_attempts_red,ground_attempts_blue
count,8505.000000,8505.000000,8505.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8505.000000,8505.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.00000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000,8484.000000
mean,4253.000000,2.352969,227.879012,0.244696,0.183404,84.910537,79.957331,39.113036,34.644743,107.476898,98.698138,58.797619,50.986445,0.435290,0.317067,1.213343,0.907944,2.963461,2.689769,149.964727,110.802469,24.838402,21.630481,65.742456,62.139439,8.054691,7.178100,11.488095,10.511669,6.219943,5.836162,7.679986,7.306223,28.005776,26.21075,68.972772,67.673503,5.157001,4.679043,7.322254,6.799623,5.950259,3.754950,8.615512,5.484206
std,2455.326353,1.018086,97.262299,0.516156,0.462507,71.428542,69.490329,33.076723,31.444780,79.748481,77.169712,45.884614,42.626718,0.872617,0.744273,1.820025,1.536353,3.787200,3.714487,190.015537,153.587094,23.080267,21.981014,58.024049,56.894779,8.990077,8.253298,12.360779,11.432873,8.054802,7.615171,9.873670,9.348571,30.068319,28.15568,69.025835,66.270997,7.630733,6.783225,10.323421,9.226653,9.821710,7.828224,14.235717,11.027956
min,1.000000,1.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2127.000000,1.000000,151.000000,0.000000,0.000000,29.000000,25.000000,14.000000,10.000000,41.000000,34.000000,22.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,3.000000,8.000000,5.000000,22.000000,18.000000,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,6.000000,5.00000,16.000000,16.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,4253.000000,3.000000,290.000000,0.000000,0.000000,68.000000,63.000000,31.000000,26.000000,96.000000,86.000000,51.000000,42.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,70.000000,43.000000,19.000000,15.000000,51.000000,47.000000,5.000000,5.000000,8.000000,7.000000,3.000000,3.000000,4.000000,4.000000,18.000000,17.00000,47.000000,47.000000,2.000000,2.000000,4.000000,3.000000,2.000000,1.000000,3.000000,1.000000
75%,6379.000000,3.000000,300.000000,0.000000,0.000000,122.000000,117.000000,56.000000,50.000000,157.000000,146.000000,84.000000,75.000000,1.000000,0.000000,2.000000,1.000000,4.000000,4.000000,226.000000,163.000000,35.000000,31.000000,93.000000,90.000000,12.000000,10.000000,17.000000,15.000000,9.000000,8.000000,11.000000,10.000000,41.000000,38.00000,102.000000,100.000000,7.000000,6.000000,10.000000,9.000000,8.000000,4.000000,11.000000,6.000000
max,8505.000000,5.000000,1080.000000,5.000000,6.000000,744.000000,510.000000,445.000000,241.000000,746.000000,567.000000,447.000000,529.000000,10.000000,7.000000,21.000000,12.000000,37.000000,49.000000,1338.000000,1300.000000,274.000000,187.000000,553.000000,437.000000,117.000000,92.000000,133.000000,112.000000,78.000000,95.000000,101.000000,102.000000,439.000000,225.00000,737.000000,504.000000,95.000000,78.000000,115.000000,89.000000,97.000000,136.000000,141.000000,163.000000

In [7]:
df_events.isnull().sum()

id                               0
event_date                       0
event_name                       0
fighter_red                     21
fighter_blue                    21
round                            0
time                             0
weight_class                     0
win_method                       0
winner                         151
stance_red                      42
stance_blue                     79
knockdowns_red                  21
knockdowns_blue                 21
sig_attempts_red                21
sig_attempts_blue               21
sig_strikes_red                 21
sig_strikes_blue                21
total_strikes_attempts_red      21
total_strikes_attempts_blue     21
total_strikes_red               21
total_strikes_blue              21
sub_attempts_red                21
sub_attempts_blue               21
takedowns_red                   21
takedowns_blue                  21
takedown_attempts_red           21
takedown_attempts_blue          21
control_time_red                 0
control_time_blue                0
head_strikes_red                21
head_strikes_blue               21
head_attempts_red               21
head_attempts_blue              21
body_strikes_red                21
body_strikes_blue               21
body_attempts_red               21
body_attempts_blue              21
leg_strikes_red                 21
leg_strikes_blue                21
leg_attempts_red                21
leg_attempts_blue               21
distance_red                    21
distance_blue                   21
distance_attempts_red           21
distance_attempts_blue          21
clinch_strikes_red              21
clinch_strikes_blue             21
clinch_attempts_red             21
clinch_attempts_blue            21
ground_strikes_red              21
ground_strikes_blue             21
ground_attempts_red             21
ground_attempts_blue            21
dtype: int64

Convert date to datetime

In [8]:
df_events['event_date'] = pd.to_datetime(df_events['event_date'], format="%Y-%m-%d")

Find Duplicates

In [9]:
df_events[df_events.duplicated(keep=False)]

Empty DataFrame
Columns: [id, event_date, event_name, fighter_red, fighter_blue, round, time, weight_class, win_method, winner, stance_red, stance_blue, knockdowns_red, knockdowns_blue, sig_attempts_red, sig_attempts_blue, sig_strikes_red, sig_strikes_blue, total_strikes_attempts_red, total_strikes_attempts_blue, total_strikes_red, total_strikes_blue, sub_attempts_red, sub_attempts_blue, takedowns_red, takedowns_blue, takedown_attempts_red, takedown_attempts_blue, control_time_red, control_time_blue, head_strikes_red, head_strikes_blue, head_attempts_red, head_attempts_blue, body_strikes_red, body_strikes_blue, body_attempts_red, body_attempts_blue, leg_strikes_red, leg_strikes_blue, leg_attempts_red, leg_attempts_blue, distance_red, distance_blue, distance_attempts_red, distance_attempts_blue, clinch_strikes_red, clinch_strikes_blue, clinch_attempts_red, clinch_attempts_blue, ground_strikes_red, ground_strikes_blue, ground_attempts_red, ground_attempts_blue]
Index: []

In [10]:
df_events = df_events.drop_duplicates()

Find missing values

In [11]:
missing_df = pd.DataFrame({
    'missing_count': df_events.isnull().sum(),
    'missing_percent': round((df_events.isnull().sum() / len(df_events)) * 100, 2)
}).sort_values(by='missing_percent', ascending=False)

missing_df

                             missing_count  missing_percent
winner                                 151             1.78
stance_blue                             79             0.93
stance_red                              42             0.49
knockdowns_red                          21             0.25
fighter_blue                            21             0.25
fighter_red                             21             0.25
total_strikes_attempts_red              21             0.25
total_strikes_attempts_blue             21             0.25
total_strikes_red                       21             0.25
sig_strikes_blue                        21             0.25
knockdowns_blue                         21             0.25
sig_strikes_red                         21             0.25
sig_attempts_blue                       21             0.25
sig_attempts_red                        21             0.25
total_strikes_blue                      21             0.25
head_strikes_blue                       21             0.25
takedown_attempts_blue                  21             0.25
takedown_attempts_red                   21             0.25
takedowns_blue                          21             0.25
takedowns_red                           21             0.25
sub_attempts_blue                       21             0.25
sub_attempts_red                        21             0.25
clinch_strikes_red                      21             0.25
clinch_strikes_blue                     21             0.25
leg_attempts_red                        21             0.25
leg_attempts_blue                       21             0.25
distance_red                            21             0.25
distance_blue                           21             0.25
distance_attempts_red                   21             0.25
head_strikes_red                        21             0.25
body_strikes_red                        21             0.25
body_strikes_blue                       21             0.25
head_attempts_red                       21             0.25
head_attempts_blue                      21             0.25
body_attempts_red                       21             0.25
body_attempts_blue                      21             0.25
leg_strikes_blue                        21             0.25
leg_strikes_red                         21             0.25
ground_strikes_red                      21             0.25
ground_strikes_blue                     21             0.25
clinch_attempts_red                     21             0.25
clinch_attempts_blue                    21             0.25
ground_attempts_red                     21             0.25
ground_attempts_blue                    21             0.25
distance_attempts_blue                  21             0.25
event_name                               0             0.00
time                                     0             0.00
win_method                               0             0.00
weight_class                             0             0.00
round                                    0             0.00
event_date                               0             0.00
id                                       0             0.00
control_time_red                         0             0.00
control_time_blue                        0             0.00

Remove null values from events that also on the official site do not have any stats.

Both fighters are null values.

In [12]:
df_events[(df_events['fighter_red'].isna()) & (df_events['fighter_blue'].isna())]

,id,event_date,event_name,fighter_red,fighter_blue,round,time,weight_class,win_method,winner,stance_red,stance_blue,knockdowns_red,knockdowns_blue,sig_attempts_red,sig_attempts_blue,sig_strikes_red,sig_strikes_blue,total_strikes_attempts_red,total_strikes_attempts_blue,total_strikes_red,total_strikes_blue,sub_attempts_red,sub_attempts_blue,takedowns_red,takedowns_blue,takedown_attempts_red,takedown_attempts_blue,control_time_red,control_time_blue,head_strikes_red,head_strikes_blue,head_attempts_red,head_attempts_blue,body_strikes_red,body_strikes_blue,body_attempts_red,body_attempts_blue,leg_strikes_red,leg_strikes_blue,leg_attempts_red,leg_attempts_blue,distance_red,distance_blue,distance_attempts_red,distance_attempts_blue,clinch_strikes_red,clinch_strikes_blue,clinch_attempts_red,clinch_attempts_blue,ground_strikes_red,ground_strikes_blue,ground_attempts_red,ground_attempts_blue
24,25,1994-12-16,UFC 4: Revenge of the Warriors,NaN,NaN,1,14,Open Weight,Submission,Joe Charles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,1994-12-16,UFC 4: Revenge of the Warriors,NaN,NaN,1,295,Open Weight,KO/TKO,Marcus Bossett,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,1995-07-14,UFC 6: Clash of the Titans,NaN,NaN,1,186,Open Weight,KO/TKO,Anthony Macias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,1995-07-14,UFC 6: Clash of the Titans,NaN,NaN,1,121,Open Weight,KO/TKO,Joel Sutton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,55,1995-09-08,UFC 7: The Brawl in Buffalo,NaN,NaN,1,326,Open Weight,KO/TKO,Onassis Parungao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,57,1995-09-08,UFC 7: The Brawl in Buffalo,NaN,NaN,1,48,Open Weight,TKO - Doctor's Stoppage,Joel Sutton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,65,1995-12-16,UFC - Ultimate Ultimate '95,NaN,NaN,1,329,Open Weight,Submission,Mark Hall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,71,1995-12-16,UFC - Ultimate Ultimate '95,NaN,NaN,1,278,Open Weight,Submission,Joe Charles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,73,1996-02-16,UFC 8: David vs Goliath,NaN,NaN,1,50,Open Weight,KO/TKO,Sam Adkins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,94,1996-07-12,UFC 10: The Tournament,NaN,NaN,2,180,Open Weight,Decision - Unanimous,Sam Adkins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,101,1996-09-20,UFC 11: The Proving Ground,NaN,NaN,1,93,Open Weight,KO/TKO,Roberto Traven,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,102,1996-09-20,UFC 11: The Proving Ground,NaN,NaN,1,105,Open Weight,Submission,Scott Ferrozzo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,106,1996-12-07,UFC - Ultimate Ultimate '96,NaN,NaN,1,286,Open Weight,KO/TKO,Tai Bowden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,112,1996-12-07,UFC - Ultimate Ultimate '96,NaN,NaN,1,105,Open Weight,KO/TKO,Mark Hall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,114,1996-12-07,UFC - Ultimate Ultimate '96,NaN,NaN,1,97,Open Weight,Submission,Steve Nelmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,115,1997-02-07,UFC 12: Judgement Day,NaN,NaN,1,48,Lightweight,KO/TKO,Nick Sanzo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,118,1997-02-07,UFC 12: Judgement Day,NaN,NaN,1,14,Heavyweight,Submission,Justin Martin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,157,1998-03-13,UFC 16: Battle in the Bayou,NaN,NaN,1,75,Lightweight,KO/TKO,Laverne Clark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,158,1998-03-13,UFC 16: Battle in the Bayou,NaN,NaN,1,80,Lightweight,Submission,Chris Brennan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,171,1998-05-15,UFC 17: Redemption,NaN,NaN,2,180,Heavyweight,Decision - Unanimous,Andre Roberts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,177,1998-10-16,UFC - Ultimate Brazil,NaN,NaN,1,627,Lightweight,KO/TKO,Cesar Marscucci,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_events = df_events[~((df_events['fighter_red'].isna()) & (df_events['fighter_blue'].isna()))]

In [14]:
missing_df = pd.DataFrame({
    'missing_count': df_events.isnull().sum(),
    'missing_percent': round((df_events.isnull().sum() / len(df_events)) * 100, 2)
}).sort_values(by='missing_percent', ascending=False)

missing_df

                             missing_count  missing_percent
winner                                 151             1.78
stance_blue                             58             0.68
stance_red                              21             0.25
event_name                               0             0.00
id                                       0             0.00
event_date                               0             0.00
round                                    0             0.00
fighter_blue                             0             0.00
fighter_red                              0             0.00
time                                     0             0.00
win_method                               0             0.00
weight_class                             0             0.00
knockdowns_red                           0             0.00
knockdowns_blue                          0             0.00
sig_attempts_red                         0             0.00
sig_attempts_blue                        0             0.00
sig_strikes_red                          0             0.00
sig_strikes_blue                         0             0.00
total_strikes_attempts_red               0             0.00
total_strikes_attempts_blue              0             0.00
total_strikes_red                        0             0.00
total_strikes_blue                       0             0.00
sub_attempts_red                         0             0.00
sub_attempts_blue                        0             0.00
takedowns_red                            0             0.00
takedowns_blue                           0             0.00
takedown_attempts_red                    0             0.00
takedown_attempts_blue                   0             0.00
control_time_red                         0             0.00
control_time_blue                        0             0.00
head_strikes_red                         0             0.00
head_strikes_blue                        0             0.00
head_attempts_red                        0             0.00
head_attempts_blue                       0             0.00
body_strikes_red                         0             0.00
body_strikes_blue                        0             0.00
body_attempts_red                        0             0.00
body_attempts_blue                       0             0.00
leg_strikes_red                          0             0.00
leg_strikes_blue                         0             0.00
leg_attempts_red                         0             0.00
leg_attempts_blue                        0             0.00
distance_red                             0             0.00
distance_blue                            0             0.00
distance_attempts_red                    0             0.00
distance_attempts_blue                   0             0.00
clinch_strikes_red                       0             0.00
clinch_strikes_blue                      0             0.00
clinch_attempts_red                      0             0.00
clinch_attempts_blue                     0             0.00
ground_strikes_red                       0             0.00
ground_strikes_blue                      0             0.00
ground_attempts_red                      0             0.00
ground_attempts_blue                     0             0.00

Drop fights where winner is null. These fight outcomes rarely happen and are usually contributed to fighters that can not continue the fight or draws.

In [15]:
df_events[df_events[['winner']].isnull().all(axis=1)].tail(10)

,id,event_date,event_name,fighter_red,fighter_blue,round,time,weight_class,win_method,winner,stance_red,stance_blue,knockdowns_red,knockdowns_blue,sig_attempts_red,sig_attempts_blue,sig_strikes_red,sig_strikes_blue,total_strikes_attempts_red,total_strikes_attempts_blue,total_strikes_red,total_strikes_blue,sub_attempts_red,sub_attempts_blue,takedowns_red,takedowns_blue,takedown_attempts_red,takedown_attempts_blue,control_time_red,control_time_blue,head_strikes_red,head_strikes_blue,head_attempts_red,head_attempts_blue,body_strikes_red,body_strikes_blue,body_attempts_red,body_attempts_blue,leg_strikes_red,leg_strikes_blue,leg_attempts_red,leg_attempts_blue,distance_red,distance_blue,distance_attempts_red,distance_attempts_blue,clinch_strikes_red,clinch_strikes_blue,clinch_attempts_red,clinch_attempts_blue,ground_strikes_red,ground_strikes_blue,ground_attempts_red,ground_attempts_blue
7503,7504,2024-02-10,UFC Fight Night: Hermansson vs. Pyfer,Daniel Marcos,Aoriqileng,2,208,Bantamweight,Could Not Continue,NaN,Orthodox,Orthodox,0.0,0.0,126.0,95.0,81.0,45.0,129.0,96.0,84.0,45.0,0.0,0.0,0.0,0.0,0.0,0.0,28,38,50.0,26.0,84.0,71.0,12.0,10.0,19.0,12.0,19.0,9.0,23.0,12.0,69.0,43.0,113.0,93.0,5.0,2.0,6.0,2.0,7.0,0.0,7.0,0.0
7568,7569,2024-03-16,UFC Fight Night: Tuivasa vs. Tybura,Bryan Battle,Ange Loosa,2,60,Welterweight,Could Not Continue,NaN,Orthodox,Orthodox,0.0,0.0,75.0,54.0,27.0,23.0,78.0,58.0,28.0,26.0,0.0,0.0,1.0,0.0,2.0,1.0,93,0,16.0,6.0,56.0,34.0,10.0,8.0,18.0,9.0,1.0,9.0,1.0,11.0,24.0,22.0,69.0,53.0,3.0,1.0,5.0,1.0,0.0,0.0,1.0,0.0
7733,7734,2024-07-13,UFC Fight Night: Namajunas vs. Cortez,Abdul Razak Alhassan,Cody Brundage,1,37,Middleweight,Could Not Continue,NaN,Orthodox,Orthodox,0.0,0.0,30.0,2.0,23.0,1.0,35.0,2.0,24.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,27,3,23.0,1.0,30.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,0.0,4.0,0.0,19.0,0.0,26.0,0.0
8014,8015,2025-02-08,UFC 312: Du Plessis vs. Strickland 2,Jimmy Crute,Rodolfo Bellato,3,300,Light Heavyweight,Decision - Majority,NaN,Orthodox,Orthodox,1.0,0.0,209.0,141.0,106.0,89.0,247.0,148.0,139.0,95.0,0.0,0.0,0.0,1.0,3.0,2.0,232,29,93.0,36.0,190.0,76.0,8.0,24.0,10.0,29.0,5.0,29.0,9.0,36.0,77.0,85.0,170.0,136.0,11.0,4.0,13.0,5.0,18.0,0.0,26.0,0.0
8211,8212,2025-06-14,UFC Fight Night: Usman vs. Buckley,Paul Craig,Rodolfo Bellato,1,299,Light Heavyweight,Could Not Continue,NaN,Orthodox,Orthodox,0.0,0.0,27.0,20.0,17.0,10.0,52.0,27.0,40.0,16.0,0.0,0.0,0.0,1.0,6.0,1.0,34,55,7.0,2.0,16.0,11.0,10.0,2.0,11.0,2.0,0.0,6.0,0.0,7.0,14.0,9.0,23.0,17.0,2.0,0.0,3.0,0.0,1.0,1.0,1.0,3.0
8214,8215,2025-06-14,UFC Fight Night: Usman vs. Buckley,Mansur Abdul-Malik,Cody Brundage,3,36,Middleweight,Overturned,NaN,Orthodox,Orthodox,0.0,0.0,73.0,67.0,25.0,30.0,73.0,67.0,25.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,7,1,17.0,18.0,55.0,49.0,3.0,2.0,13.0,8.0,5.0,10.0,5.0,10.0,18.0,29.0,60.0,66.0,0.0,1.0,0.0,1.0,7.0,0.0,13.0,0.0
8344,8345,2025-09-13,UFC Fight Night: Lopes vs. Silva,Zach Reese,Sedriques Dumas,1,51,Middleweight,Could Not Continue,NaN,Switch,Orthodox,0.0,0.0,7.0,10.0,2.0,3.0,7.0,10.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,1.0,3.0,8.0,1.0,0.0,3.0,0.0,1.0,2.0,1.0,2.0,2.0,3.0,7.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8408,8409,2025-10-25,UFC 321: Aspinall vs. Gane,Tom Aspinall,Ciryl Gane,1,275,UFC Heavyweight Title,Could Not Continue,NaN,Orthodox,Orthodox,0.0,0.0,39.0,40.0,27.0,30.0,39.0,40.0,27.0,30.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,14.0,8.0,25.0,16.0,5.0,9.0,6.0,11.0,8.0,13.0,8.0,13.0,27.0,30.0,39.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8473,8474,2025-12-06,UFC 323: Dvalishvili vs. Yan 2,Jan Blachowicz,Bogdan Guskov,3,300,Light Heavyweight,Decision - Majority,NaN,Orthodox,Orthodox,1.0,1.0,149.0,140.0,84.0,80.0,173.0,160.0,100.0,98.0,1.0,0.0,0.0,0.0,0.0,0.0,8,249,56.0,69.0,112.0,127.0,11.0,2.0,17.0,3.0,17.0,9.0,20.0,10.0,74.0,52.0,135.0,96.0,2.0,0.0,3.0,0.0,8.0,28.0,11.0,44.0
8482,8483,2025-12-13,UFC Fight Night: Royval vs. Kape,Kennedy Nzechukwu,Marcus Buchecha,3,300,Heavyweight,Decision - Unanimous,NaN,Southpaw,Orthodox,0.0,0.0,48.0,44.0,24.0,27.0,87.0,66.0,58.0,47.0,0.0,0.0,0.0,3.0,0.0,13.0,217,380,21.0,23.0,43.0,38.0,3.0,4.0,5.0,6.0,0.0,0.0,0.0,0.0,13.0,2.0,32.0,12.0,2.0,2.0,2.0,4.0,9.0,23.0,14.0,28.0

Calculate the fights where there are no winners per year

In [16]:
# Extract year
df_events = df_events.copy()
df_events['year'] = df_events['event_date'].dt.year

# Total fights per year
total_fights = df_events.groupby('year').size()

# Total no-winner fights per year (count where winner is null)
no_winners = df_events.groupby('year')['winner'].apply(lambda x: x.isnull().sum())

# Average of no winners per year (ratio)
avg_no_winners = no_winners / total_fights

# Combine into summary DataFrame
df_summary = pd.DataFrame({
    'year': total_fights.index,
    'avg_no_winners': avg_no_winners.values,
    'total_fights': total_fights.values,
    'total_no_winners': no_winners.values
}).reset_index(drop=True)

df_summary

    year  avg_no_winners  total_fights  total_no_winners
0   1994        0.000000            29                 0
1   1995        0.058824            34                 2
2   1996        0.000000            36                 0
3   1997        0.025641            39                 1
4   1998        0.000000            21                 0
5   1999        0.045455            44                 2
6   2000        0.023256            43                 1
7   2001        0.025000            40                 1
8   2002        0.018868            53                 1
9   2003        0.048780            41                 2
10  2004        0.000000            39                 0
11  2005        0.012500            80                 1
12  2006        0.000000           158                 0
13  2007        0.011696           171                 2
14  2008        0.000000           201                 0
15  2009        0.009302           215                 2
16  2010        0.011858           253                 3
17  2011        0.016667           300                 5
18  2012        0.023460           341                 8
19  2013        0.025907           386                10
20  2014        0.017893           503                 9
21  2015        0.019027           473                 9
22  2016        0.020284           493                10
23  2017        0.024070           457                11
24  2018        0.010549           474                 5
25  2019        0.019380           516                10
26  2020        0.026316           456                12
27  2021        0.023576           509                12
28  2022        0.009785           511                 5
29  2023        0.030769           520                16
30  2024        0.007737           517                 4
31  2025        0.013462           520                 7
32  2026        0.000000            11                 0

In [17]:
df_events = df_events[~df_events[['winner']].isnull().all(axis=1)]

Fill missing stance values with the highest occuring one

In [18]:
df_events['stance_blue'].unique()

<StringArray>
['Orthodox', 'Southpaw', nan, 'Open Stance', 'Sideways', 'Switch']
Length: 6, dtype: str

In [19]:
df_events['stance_red'].unique()

<StringArray>
['Southpaw', 'Orthodox', nan, 'Sideways', 'Switch', 'Open Stance']
Length: 6, dtype: str

In [20]:
df_events[df_events[['stance_blue']].isnull().all(axis=1)].tail(5)

,id,event_date,event_name,fighter_red,fighter_blue,round,time,weight_class,win_method,winner,stance_red,stance_blue,knockdowns_red,knockdowns_blue,sig_attempts_red,sig_attempts_blue,sig_strikes_red,sig_strikes_blue,total_strikes_attempts_red,total_strikes_attempts_blue,total_strikes_red,total_strikes_blue,sub_attempts_red,sub_attempts_blue,takedowns_red,takedowns_blue,takedown_attempts_red,takedown_attempts_blue,control_time_red,control_time_blue,head_strikes_red,head_strikes_blue,head_attempts_red,head_attempts_blue,body_strikes_red,body_strikes_blue,body_attempts_red,body_attempts_blue,leg_strikes_red,leg_strikes_blue,leg_attempts_red,leg_attempts_blue,distance_red,distance_blue,distance_attempts_red,distance_attempts_blue,clinch_strikes_red,clinch_strikes_blue,clinch_attempts_red,clinch_attempts_blue,ground_strikes_red,ground_strikes_blue,ground_attempts_red,ground_attempts_blue,year
3746,3747,2016-07-09,UFC 200: Tate vs Nunes,Sage Northcutt,Enrique Marin,3,300,Lightweight,Decision - Unanimous,Sage Northcutt,Orthodox,NaN,0.0,0.0,66.0,36.0,41.0,16.0,135.0,48.0,106.0,26.0,1.0,2.0,0.0,4.0,2.0,10.0,262,448,36.0,12.0,59.0,32.0,3.0,2.0,5.0,2.0,2.0,2.0,2.0,2.0,14.0,12.0,33.0,31.0,13.0,2.0,17.0,3.0,14.0,2.0,16.0,2.0,2016
3796,3797,2016-08-06,UFC Fight Night: Rodriguez vs. Caceres,Teruto Ishihara,Horacio Gutierrez,1,152,Featherweight,KO/TKO,Teruto Ishihara,Southpaw,NaN,1.0,0.0,25.0,18.0,13.0,5.0,25.0,18.0,13.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0,6,0,7.0,1.0,17.0,14.0,3.0,0.0,5.0,0.0,3.0,4.0,3.0,4.0,8.0,5.0,19.0,18.0,0.0,0.0,0.0,0.0,5.0,0.0,6.0,0.0,2016
8456,8457,2025-11-22,UFC Fight Night: Tsarukyan vs. Hooker,Nicolas Dalby,Saygid Izagakhmaev,3,300,Welterweight,Decision - Split,Nicolas Dalby,Orthodox,NaN,0.0,0.0,63.0,34.0,26.0,20.0,140.0,88.0,87.0,65.0,0.0,0.0,0.0,4.0,2.0,10.0,389,318,13.0,11.0,41.0,23.0,8.0,9.0,16.0,10.0,5.0,0.0,6.0,1.0,11.0,8.0,40.0,19.0,13.0,10.0,21.0,12.0,2.0,2.0,2.0,3.0,2025
8483,8484,2025-12-13,UFC Fight Night: Royval vs. Kape,Joanderson Brito,Isaac Thomson,3,300,Featherweight,Decision - Unanimous,Joanderson Brito,Orthodox,NaN,0.0,0.0,57.0,47.0,33.0,21.0,93.0,164.0,66.0,127.0,2.0,0.0,8.0,4.0,12.0,5.0,479,180,16.0,14.0,36.0,33.0,7.0,6.0,10.0,10.0,10.0,1.0,11.0,4.0,19.0,14.0,36.0,37.0,7.0,6.0,10.0,8.0,7.0,1.0,11.0,2.0,2025
8484,8485,2025-12-13,UFC Fight Night: Royval vs. Kape,King Green,Lance Gibson Jr.,3,300,Catch Weight,Decision - Split,King Green,Orthodox,NaN,0.0,0.0,141.0,72.0,65.0,30.0,150.0,77.0,74.0,35.0,0.0,0.0,1.0,2.0,2.0,3.0,44,70,25.0,9.0,77.0,39.0,24.0,8.0,40.0,14.0,16.0,13.0,24.0,19.0,56.0,27.0,129.0,66.0,1.0,3.0,1.0,6.0,8.0,0.0,11.0,0.0,2025

Build a fighter dataframe from both red and blue stance columns

In [21]:
df_fighters_red = df_events[['fighter_red', 'stance_red']].rename(
    columns={'fighter_red': 'fighter', 'stance_red': 'stance'}
)
df_fighters_blue = df_events[['fighter_blue', 'stance_blue']].rename(
    columns={'fighter_blue': 'fighter', 'stance_blue': 'stance'}
)

# Combine into one fighter dataframe
df_fighters = pd.concat([df_fighters_red, df_fighters_blue], ignore_index=True)

# Drop duplicate fighters (keep their first known stance)
df_fighters = df_fighters.drop_duplicates(subset=['fighter'], keep='first')

# Count unique stances across fighters
stance_counts = df_fighters['stance'].value_counts(dropna=True)

print("Unique stance counts across fighters:\n", stance_counts)

Unique stance counts across fighters:
 stance
Orthodox       1958
Southpaw        441
Switch          150
Open Stance       6
Sideways          3
Name: count, dtype: int64

In [22]:
top_stances = stance_counts.index[:1].tolist()

df_events['stance_red'] = df_events['stance_red'].fillna(top_stances[0])
df_events['stance_blue'] = df_events['stance_blue'].fillna(top_stances[0])

In [23]:
df_events.isnull().sum()

id                             0
event_date                     0
event_name                     0
fighter_red                    0
fighter_blue                   0
round                          0
time                           0
weight_class                   0
win_method                     0
winner                         0
stance_red                     0
stance_blue                    0
knockdowns_red                 0
knockdowns_blue                0
sig_attempts_red               0
sig_attempts_blue              0
sig_strikes_red                0
sig_strikes_blue               0
total_strikes_attempts_red     0
total_strikes_attempts_blue    0
total_strikes_red              0
total_strikes_blue             0
sub_attempts_red               0
sub_attempts_blue              0
takedowns_red                  0
takedowns_blue                 0
takedown_attempts_red          0
takedown_attempts_blue         0
control_time_red               0
control_time_blue              0
head_strikes_red               0
head_strikes_blue              0
head_attempts_red              0
head_attempts_blue             0
body_strikes_red               0
body_strikes_blue              0
body_attempts_red              0
body_attempts_blue             0
leg_strikes_red                0
leg_strikes_blue               0
leg_attempts_red               0
leg_attempts_blue              0
distance_red                   0
distance_blue                  0
distance_attempts_red          0
distance_attempts_blue         0
clinch_strikes_red             0
clinch_strikes_blue            0
clinch_attempts_red            0
clinch_attempts_blue           0
ground_strikes_red             0
ground_strikes_blue            0
ground_attempts_red            0
ground_attempts_blue           0
year                           0
dtype: int64

Convert numerical values to int

In [24]:
for col in df_events.select_dtypes(include=['number']).columns:
    df_events[col] = df_events[col].astype('int64')

Convert winner column to 1 if winner is red or 0 if winner is blue

In [25]:
df_events['winner'] = (df_events['winner'] == df_events['fighter_red']).astype(int)
df_events.tail()

,id,event_date,event_name,fighter_red,fighter_blue,round,time,weight_class,win_method,winner,stance_red,stance_blue,knockdowns_red,knockdowns_blue,sig_attempts_red,sig_attempts_blue,sig_strikes_red,sig_strikes_blue,total_strikes_attempts_red,total_strikes_attempts_blue,total_strikes_red,total_strikes_blue,sub_attempts_red,sub_attempts_blue,takedowns_red,takedowns_blue,takedown_attempts_red,takedown_attempts_blue,control_time_red,control_time_blue,head_strikes_red,head_strikes_blue,head_attempts_red,head_attempts_blue,body_strikes_red,body_strikes_blue,body_attempts_red,body_attempts_blue,leg_strikes_red,leg_strikes_blue,leg_attempts_red,leg_attempts_blue,distance_red,distance_blue,distance_attempts_red,distance_attempts_blue,clinch_strikes_red,clinch_strikes_blue,clinch_attempts_red,clinch_attempts_blue,ground_strikes_red,ground_strikes_blue,ground_attempts_red,ground_attempts_blue,year
8500,8501,2026-01-24,UFC 324: Gaethje vs. Pimblett,Natalia Silva,Rose Namajunas,3,300,Women's Flyweight,Decision - Unanimous,1,Southpaw,Orthodox,0,0,133,94,51,26,147,119,63,46,0,0,1,1,2,5,84,129,25,11,95,64,8,3,14,13,18,12,24,17,50,26,132,92,1,0,1,2,0,0,0,0,2026
8501,8502,2026-01-24,UFC 324: Gaethje vs. Pimblett,Justin Gaethje,Paddy Pimblett,5,300,UFC Interim Lightweight Title,Decision - Unanimous,1,Orthodox,Orthodox,2,0,254,311,144,156,313,326,200,170,0,0,3,0,3,5,355,48,120,83,222,221,15,48,21,63,9,25,11,27,102,140,198,284,20,16,27,27,22,0,29,0,2026
8502,8503,2026-01-24,UFC 324: Gaethje vs. Pimblett,Waldo Cortes Acosta,Derrick Lewis,2,194,Heavyweight,KO/TKO,1,Orthodox,Orthodox,1,0,62,43,44,8,64,43,46,8,0,0,1,0,1,0,28,0,35,6,53,37,5,2,5,5,4,0,4,1,27,8,45,43,1,0,1,0,16,0,16,0,2026
8503,8504,2026-01-24,UFC 324: Gaethje vs. Pimblett,Alex Perez,Charles Johnson,1,196,Flyweight,KO/TKO,1,Orthodox,Switch,2,0,75,25,39,8,94,25,55,8,0,0,0,0,0,1,14,0,27,4,60,14,9,3,10,9,3,1,5,2,33,8,67,25,4,0,6,0,2,0,2,0,2026
8504,8505,2026-01-24,UFC 324: Gaethje vs. Pimblett,Adam Fugitt,Ty Miller,1,299,Welterweight,KO/TKO,0,Southpaw,Orthodox,0,1,73,121,36,59,76,129,39,65,0,0,0,0,2,0,0,3,10,55,42,115,21,4,26,6,5,0,5,0,30,55,67,115,6,3,6,4,0,1,0,2,2026

Normalize weight classes

In [26]:
df_events["weight_class"].value_counts()

weight_class
Lightweight                                            1347
Welterweight                                           1292
Middleweight                                           1049
Featherweight                                           787
Bantamweight                                            703
                                                       ...
Road to UFC 3 Bantamweight Tournament Title               1
Road to UFC 3 Flyweight Tournament Title                  1
Road to UFC 3 Women's Strawweight Tournament Title        1
Ultimate Fighter 33 Flyweight Tournament Title            1
Ultimate Fighter 33 Welterweight Tournament Title         1
Name: count, Length: 120, dtype: int64

In [27]:
def clean_text(val: str) -> str:
    if not isinstance(val, str):
        return val
    val = val.strip().lower()  # lowercase + trim
    val = re.sub(r"\s+", " ", val)  # collapse multiple spaces
    val = val.replace("womens", "women's")  # normalize missing apostrophe
    val = val.replace("women ", "women's ") # normalize if missing "'s"
    return val

# master map of cleaned values → canonical
mapping = {
    "lightweight": "Lightweight",
    "welterweight": "Welterweight",
    "middleweight": "Middleweight",
    "featherweight": "Featherweight",
    "bantamweight": "Bantamweight",
    "heavyweight": "Heavyweight",
    "light heavyweight": "Light Heavyweight",
    "flyweight": "Flyweight",
    "women's strawweight": "Women's Strawweight",
    "women's flyweight": "Women's Flyweight",
    "women's bantamweight": "Women's Bantamweight",
    "open weight": "Open Weight",
    "catch weight": "Catch Weight"
}

def normalize_weight_class(val):
    # clean first
    cleaned = clean_text(val)

    # if it matches exactly after cleaning
    if cleaned in mapping:
        return mapping[cleaned]
    
    # fuzzy keyword matching for tournament-style
    if "heavyweight" in cleaned and "light" not in cleaned:
        return "Heavyweight"
    elif "lightweight" in cleaned and "feather" not in cleaned:
        return "Lightweight"
    elif "middleweight" in cleaned:
        return "Middleweight"
    elif "featherweight" in cleaned:
        return "Featherweight"
    elif "bantamweight" in cleaned:
        # if it’s a women’s version
        if "women" in cleaned:
            return "Women's Bantamweight"
        return "Bantamweight"
    elif "flyweight" in cleaned:
        if "women" in cleaned:
            return "Women's Flyweight"
        return "Flyweight"
    elif "strawweight" in cleaned:
        return "Women's Strawweight"
    
    # default
    return "Open Weight"

In [28]:
df_events["weight_class"] = df_events["weight_class"].apply(normalize_weight_class)

In [29]:
df_events["weight_class"].value_counts()

weight_class
Lightweight             1398
Welterweight            1292
Middleweight            1103
Featherweight            849
Heavyweight              741
Bantamweight             738
Light Heavyweight        663
Flyweight                395
Women's Strawweight      355
Women's Flyweight        264
Women's Bantamweight     234
Open Weight              225
Catch Weight              76
Name: count, dtype: int64

Drop columns and reset index

In [32]:
df_events.drop(columns=['id', 'year'], inplace=True)

df_events = df_events.reset_index(drop=True)

Normalize names for future matching

In [34]:
def normalize_name(name):

    if pd.isna(name):
        return ""
    
    # Convert to string if not already
    name = str(name)

    # Remove extra whitespace
    #name = name.strip()

    # Normalize unicode characters
    name = unicodedata.normalize('NFKD', name)
    name = ''.join(c for c in name if not unicodedata.combining(c))

    # Convert to lower
    name = name.lower()

    # Remove apostrophes and replace with nothing or space
    #name = re.sub(r"'", "", name)

    # Remove periods and other punctuation
    name = re.sub(r'[^\w\s-]', '', name)

    # Normalize spaces (multiple spaces to single space)
    name = re.sub(r'\s+', ' ', name)

    words = name.split()

    return ' '.join(words).strip()

In [35]:
df_events[["fighter_red", "fighter_blue"]] = df_events[["fighter_red", "fighter_blue"]].map(normalize_name)

In [36]:
df_events

,event_date,event_name,fighter_red,fighter_blue,round,time,weight_class,win_method,winner,stance_red,stance_blue,knockdowns_red,knockdowns_blue,sig_attempts_red,sig_attempts_blue,sig_strikes_red,sig_strikes_blue,total_strikes_attempts_red,total_strikes_attempts_blue,total_strikes_red,total_strikes_blue,sub_attempts_red,sub_attempts_blue,takedowns_red,takedowns_blue,takedown_attempts_red,takedown_attempts_blue,control_time_red,control_time_blue,head_strikes_red,head_strikes_blue,head_attempts_red,head_attempts_blue,body_strikes_red,body_strikes_blue,body_attempts_red,body_attempts_blue,leg_strikes_red,leg_strikes_blue,leg_attempts_red,leg_attempts_blue,distance_red,distance_blue,distance_attempts_red,distance_attempts_blue,clinch_strikes_red,clinch_strikes_blue,clinch_attempts_red,clinch_attempts_blue,ground_strikes_red,ground_strikes_blue,ground_attempts_red,ground_attempts_blue
0,1994-03-11,UFC 2: No Way Out,royce gracie,patrick smith,1,77,Open Weight,KO/TKO,1,Southpaw,Orthodox,0,0,4,2,4,1,11,3,11,2,0,0,1,0,2,0,0,0,3,0,3,0,0,1,0,2,1,0,1,0,0,0,0,1,1,1,1,1,3,0,3,0
1,1994-03-11,UFC 2: No Way Out,patrick smith,johnny rhodes,1,67,Open Weight,Submission,1,Orthodox,Orthodox,0,0,12,9,5,4,12,9,5,4,1,0,0,0,0,0,0,0,1,2,4,5,2,0,2,0,2,2,6,4,3,4,10,9,2,0,2,0,0,0,0,0
2,1994-03-11,UFC 2: No Way Out,royce gracie,jason delucia,1,67,Open Weight,Submission,1,Southpaw,Southpaw,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1994-03-11,UFC 2: No Way Out,remco pardoel,orlando wiet,1,89,Open Weight,KO/TKO,1,Southpaw,Southpaw,0,0,7,2,7,1,7,7,7,5,0,0,1,0,1,0,0,0,7,0,7,1,0,0,0,0,0,1,0,1,0,1,0,2,0,0,0,0,7,0,7,0
4,1994-03-11,UFC 2: No Way Out,jason delucia,scott baker,1,401,Open Weight,Submission,1,Southpaw,Orthodox,0,0,5,2,3,0,25,23,20,14,5,0,0,1,1,1,0,0,1,0,2,2,1,0,2,0,1,0,1,0,2,0,4,2,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8328,2026-01-24,UFC 324: Gaethje vs. Pimblett,natalia silva,rose namajunas,3,300,Women's Flyweight,Decision - Unanimous,1,Southpaw,Orthodox,0,0,133,94,51,26,147,119,63,46,0,0,1,1,2,5,84,129,25,11,95,64,8,3,14,13,18,12,24,17,50,26,132,92,1,0,1,2,0,0,0,0
8329,2026-01-24,UFC 324: Gaethje vs. Pimblett,justin gaethje,paddy pimblett,5,300,Lightweight,Decision - Unanimous,1,Orthodox,Orthodox,2,0,254,311,144,156,313,326,200,170,0,0,3,0,3,5,355,48,120,83,222,221,15,48,21,63,9,25,11,27,102,140,198,284,20,16,27,27,22,0,29,0
8330,2026-01-24,UFC 324: Gaethje vs. Pimblett,waldo cortes acosta,derrick lewis,2,194,Heavyweight,KO/TKO,1,Orthodox,Orthodox,1,0,62,43,44,8,64,43,46,8,0,0,1,0,1,0,28,0,35,6,53,37,5,2,5,5,4,0,4,1,27,8,45,43,1,0,1,0,16,0,16,0
8331,2026-01-24,UFC 324: Gaethje vs. Pimblett,alex perez,charles johnson,1,196,Flyweight,KO/TKO,1,Orthodox,Switch,2,0,75,25,39,8,94,25,55,8,0,0,0,0,0,1,14,0,27,4,60,14,9,3,10,9,3,1,5,2,33,8,67,25,4,0,6,0,2,0,2,0
8332,2026-01-24,UFC 324: Gaethje vs. Pimblett,adam fugitt,ty miller,1,299,Welterweight,KO/TKO,0,Southpaw,Orthodox,0,1,73,121,36,59,76,129,39,65,0,0,0,0,2,0,0,3,10,55,42,115,21,4,26,6,5,0,5,0,30,55,67,115,6,3,6,4,0,1,0,2

In [37]:
df_events.to_csv('../data/notebooks/events_cleaned.csv', index=False)

Review Stats

In [38]:
# Stats data
conn = mysql.connector.connect(
    host=os.getenv("DB_HOST"),
    user=os.getenv("DB_USER"),
    database=os.getenv("DB_NAME"),
    password=os.getenv("DB_PASSWORD")
    )

cursor = conn.cursor()

query = ("SELECT * FROM stats")

cursor.execute(query)

columns = [desc[0] for desc in cursor.description]

rows = cursor.fetchall()

df_stats = pd.DataFrame(rows, columns=columns)

cursor.close()
conn.close()

In [39]:
df_stats.tail()

,id,name,nickname,division,record,status,place_of_birth,trains_at,fighting_style,octagon_debut,age,height,weight,reach,leg_reach,wins,losses,draws,wins_by_knockout,first_round_finishes,win_by_dec,win_by_sub,sig_strikes_landed,sig_strikes_attempted,takedowns_landed,takedowns_attempted,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,sig_strikes_defense,takedown_defense,knockdown_avg,fight_time_avg,sig_strikes_standing,sig_strikes_clinch,sig_strikes_ground,head_target,body_target,leg_target
3099,3100,Zhang Lipeng,"""The Warrior""",Lightweight Division,9-9-1 (W-L-D),Not Fighting,United States,NaN,NaN,"Mar. 1, 2014",33.0,71.0,155.0,71.0,NaN,9,9,1,NaN,NaN,4.0,3.0,77.0,158.0,NaN,23.0,1.0,2.0,1.75,0.75,54.0,70.0,0.0,15:00,38.0,32.0,7.0,24.0,17.0,36.0
3100,3101,Zviad Lazishvili,NaN,Bantamweight Division,13-1-0 (W-L-D),Not Fighting,"Kobuleti, Georgia",Kaizen MMA,Freestyle,"Oct. 23, 2021",31.0,66.0,135.0,69.0,37.0,13,1,0,NaN,NaN,4.0,9.0,63.0,160.0,NaN,6.0,4.0,6.0,0.00,0.00,51.0,NaN,0.0,15:00,60.0,3.0,0.0,25.0,17.0,21.0
3101,3102,Zarah Fairn,"""Infinite""",Women's Bantamweight Division,6-5-0 (W-L-D),Active,"Paris, France",Team Figueiredo,MMA,"Oct. 5, 2019",39.0,68.0,146.0,72.0,42.0,6,5,0,4.0,4.0,2.0,0.0,171.0,543.0,NaN,2.0,5.0,7.0,0.00,0.00,46.0,60.0,0.0,09:24,160.0,11.0,0.0,128.0,26.0,17.0
3102,3103,Zubaira Tukhugov,"""Warrior""",Lightweight Division,20-6-1 (W-L-D),Not Fighting,"USSR, Russia","Tiger Muay Thai - Phuket, Thailand",Striker,"Feb. 15, 2014",32.0,68.0,157.5,68.0,38.5,20,6,1,7.0,7.0,12.0,1.0,357.0,894.0,7.0,41.0,3.0,3.0,2.13,0.00,64.0,100.0,0.4,12:31,302.0,24.0,31.0,312.0,36.0,9.0
3103,3104,Zygimantas Ramaska,NaN,Featherweight Division,9-3-0 (W-L-D),Not Fighting,Lithuania,Ukmergė Judo Club,Judo,"Aug. 24, 2024",28.0,71.0,145.5,73.0,NaN,9,3,0,5.0,5.0,0.0,4.0,6.0,10.0,NaN,NaN,1.0,2.0,0.00,2.41,30.0,33.0,0.0,06:14,2.0,4.0,0.0,5.0,1.0,0.0

In [40]:
df_stats.info()

<class 'pandas.DataFrame'>
RangeIndex: 3104 entries, 0 to 3103
Data columns (total 40 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               3104 non-null   int64
 1   name                             3104 non-null   str
 2   nickname                         1844 non-null   str
 3   division                         2991 non-null   str
 4   record                           3064 non-null   str
 5   status                           3076 non-null   str
 6   place_of_birth                   2920 non-null   str
 7   trains_at                        1033 non-null   str
 8   fighting_style                   1055 non-null   str
 9   octagon_debut                    3104 non-null   str
 10  age                              2845 non-null   float64
 11  height                           2826 non-null   float64
 12  weight                           2997 non-null   float64
 13  reach                            1990 non-null   float64
 14  leg_reach                        1708 non-null   float64
 15  wins                             3104 non-null   int64
 16  losses                           3104 non-null   int64
 17  draws                            3104 non-null   int64
 18  wins_by_knockout                 1253 non-null   float64
 19  first_round_finishes             902 non-null    float64
 20  win_by_dec                       3055 non-null   float64
 21  win_by_sub                       3055 non-null   float64
 22  sig_strikes_landed               2818 non-null   float64
 23  sig_strikes_attempted            2818 non-null   float64
 24  takedowns_landed                 923 non-null    float64
 25  takedowns_attempted              2519 non-null   float64
 26  sig_strikes_landed_per_minute    2827 non-null   float64
 27  sig_strikes_absorbed_per_minute  2827 non-null   float64
 28  takedowns_avg                    2827 non-null   float64
 29  submission_avg                   2827 non-null   float64
 30  sig_strikes_defense              2813 non-null   float64
 31  takedown_defense                 2370 non-null   float64
 32  knockdown_avg                    2827 non-null   float64
 33  fight_time_avg                   3055 non-null   str
 34  sig_strikes_standing             3055 non-null   float64
 35  sig_strikes_clinch               3055 non-null   float64
 36  sig_strikes_ground               3055 non-null   float64
 37  head_target                      3055 non-null   float64
 38  body_target                      3055 non-null   float64
 39  leg_target                       3055 non-null   float64
dtypes: float64(26), int64(4), str(10)
memory usage: 970.1 KB

In [41]:
df_stats.describe()

,id,age,height,weight,reach,leg_reach,wins,losses,draws,wins_by_knockout,first_round_finishes,win_by_dec,win_by_sub,sig_strikes_landed,sig_strikes_attempted,takedowns_landed,takedowns_attempted,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,sig_strikes_defense,takedown_defense,knockdown_avg,sig_strikes_standing,sig_strikes_clinch,sig_strikes_ground,head_target,body_target,leg_target
count,3104.000000,2845.000000,2826.000000,2997.000000,1990.000000,1708.000000,3104.000000,3104.000000,3104.000000,1253.000000,902.000000,3055.000000,3055.000000,2818.000000,2818.000000,923.000000,2519.000000,2827.000000,2827.000000,2827.000000,2827.000000,2813.000000,2370.000000,2827.000000,3055.000000,3055.000000,3055.000000,3055.000000,3055.000000,3055.000000
mean,1552.500000,36.060457,65.729653,157.699132,71.625377,40.002049,11.477771,4.392075,0.164304,6.315243,6.307095,2.484124,2.382979,246.682754,550.399574,7.166847,21.352918,3.228511,3.885745,1.492883,0.609752,52.145752,61.538819,0.391075,165.259247,31.214075,31.072340,143.498854,47.113912,36.932897
std,896.191944,7.088639,17.388354,51.117948,4.305921,2.682773,8.722537,3.758666,0.579543,4.050449,3.778544,3.422114,3.561138,314.896415,695.741924,10.226412,28.406370,1.915074,2.493026,1.771333,1.221056,10.572419,21.237217,1.850918,240.441917,47.985788,52.004782,200.166779,68.834441,57.128674
min,1.000000,19.000000,0.000000,0.000000,58.500000,32.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,4.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,776.750000,31.000000,67.000000,136.000000,69.000000,38.000000,6.000000,2.000000,0.000000,3.000000,4.000000,0.000000,0.000000,44.000000,104.000000,2.000000,4.000000,2.000000,3.000000,0.175000,0.000000,46.000000,48.000000,0.000000,17.000000,3.000000,1.000000,17.000000,5.000000,3.000000
50%,1552.500000,35.000000,70.000000,156.000000,72.000000,40.000000,11.000000,4.000000,0.000000,6.000000,6.000000,1.000000,1.000000,128.500000,282.000000,3.000000,11.000000,3.000000,3.000000,1.020000,0.230000,53.000000,63.000000,0.000000,73.000000,13.000000,10.000000,67.000000,21.000000,16.000000
75%,2328.250000,40.000000,73.000000,185.000000,74.500000,42.000000,16.000000,6.000000,0.000000,8.000000,8.000000,4.000000,4.000000,324.750000,731.000000,8.000000,26.000000,4.000000,5.000000,2.145000,0.805000,59.000000,75.000000,0.420000,220.000000,39.000000,38.500000,189.000000,61.000000,46.000000
max,3104.000000,80.000000,84.000000,415.000000,84.500000,74.000000,88.000000,24.000000,10.000000,28.000000,26.000000,32.000000,47.000000,3655.000000,7602.000000,90.000000,338.000000,32.000000,53.000000,24.110000,21.950000,100.000000,100.000000,60.000000,3222.000000,515.000000,523.000000,2363.000000,893.000000,508.000000

In [42]:
df_stats.isnull().sum()

id                                    0
name                                  0
nickname                           1260
division                            113
record                               40
status                               28
place_of_birth                      184
trains_at                          2071
fighting_style                     2049
octagon_debut                         0
age                                 259
height                              278
weight                              107
reach                              1114
leg_reach                          1396
wins                                  0
losses                                0
draws                                 0
wins_by_knockout                   1851
first_round_finishes               2202
win_by_dec                           49
win_by_sub                           49
sig_strikes_landed                  286
sig_strikes_attempted               286
takedowns_landed                   2181
takedowns_attempted                 585
sig_strikes_landed_per_minute       277
sig_strikes_absorbed_per_minute     277
takedowns_avg                       277
submission_avg                      277
sig_strikes_defense                 291
takedown_defense                    734
knockdown_avg                       277
fight_time_avg                       49
sig_strikes_standing                 49
sig_strikes_clinch                   49
sig_strikes_ground                   49
head_target                          49
body_target                          49
leg_target                           49
dtype: int64

Find Duplicates Names and Drop

In [43]:
df_stats[df_stats.duplicated('name', keep=False) == True]

,id,name,nickname,division,record,status,place_of_birth,trains_at,fighting_style,octagon_debut,age,height,weight,reach,leg_reach,wins,losses,draws,wins_by_knockout,first_round_finishes,win_by_dec,win_by_sub,sig_strikes_landed,sig_strikes_attempted,takedowns_landed,takedowns_attempted,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,sig_strikes_defense,takedown_defense,knockdown_avg,fight_time_avg,sig_strikes_standing,sig_strikes_clinch,sig_strikes_ground,head_target,body_target,leg_target
386,387,Bruno Silva,"""Bulldog""",Flyweight Division,15-7-2 (W-L-D),Active,"Piracicaba, Brazil",American Top Team,Grappler,"Sep. 7, 2019",35.0,64.0,125.5,65.0,35.0,15,7,2,6.0,4.0,4.0,5.0,399.0,787.0,2.0,55.0,4.0,5.0,2.30,0.29,52.0,63.0,1.00,10:27,331.0,26.0,42.0,226.0,94.0,79.0
391,392,Bruno Silva,"""Blindado""",Middleweight Division,23-13-0 (W-L-D),Not Fighting,Brazil,Evolucao Thai - Curitiba,Striker,"Jun. 19, 2021",35.0,72.0,187.0,74.0,42.0,23,13,0,20.0,14.0,3.0,0.0,376.0,783.0,2.0,22.0,4.0,5.0,0.77,0.00,42.0,74.0,0.31,08:51,274.0,44.0,58.0,284.0,58.0,34.0
437,438,Casey Kenney,NaN,NaN,NaN,Not Fighting,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
443,444,Casey Kenney,NaN,Bantamweight Division,16-4-1 (W-L-D),Active,"Portland, United States",NaN,MMA,"Jul. 18, 2017",32.0,67.0,136.0,70.0,36.0,16,4,1,2.0,NaN,9.0,5.0,670.0,1570.0,2.0,28.0,5.0,5.0,1.09,0.43,58.0,61.0,0.00,13:48,598.0,54.0,18.0,361.0,168.0,141.0
1379,1380,Joey Gomez,"""KO King""",Bantamweight Division,6-2-0 (W-L-D),Not Fighting,"Fairfax, United States",Team Link Hooksett,NaN,"Jan. 18, 2016",36.0,68.0,135.0,73.0,40.0,6,2,0,NaN,NaN,0.0,0.0,59.0,207.0,NaN,1.0,2.0,4.0,0.62,0.00,55.0,50.0,0.62,12:07,47.0,12.0,0.0,36.0,9.0,14.0
1381,1382,Joey Gomez,NaN,Lightweight Division,7-0-0 (W-L-D),Not Fighting,"Reno, United States",NaN,NaN,"Jan. 27, 2026",33.0,NaN,NaN,NaN,NaN,7,0,0,NaN,NaN,0.0,0.0,56.0,113.0,NaN,7.0,4.0,3.0,2.00,0.00,51.0,NaN,0.00,15:00,47.0,0.0,9.0,54.0,2.0,0.0
2425,2426,Richie Vaculik,NaN,NaN,NaN,Not Fighting,Australia,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2427,2428,Richie Vaculik,"""Vas""",Flyweight Division,10-5-0 (W-L-D),Not Fighting,"Sydney, Australia",NaN,NaN,"Dec. 7, 2013",40.0,66.0,125.0,69.0,41.0,10,5,0,NaN,NaN,1.0,6.0,166.0,355.0,NaN,20.0,4.0,4.0,3.00,1.00,57.0,32.0,0.00,11:15,132.0,23.0,11.0,107.0,31.0,28.0

Drop duplicates that have the most NaN values in the row

In [44]:
df_stats = df_stats.assign(nan_count=df_stats.isnull().sum(axis=1)) \
            .sort_values(['name', 'nan_count']) \
            .drop_duplicates('name', keep='first') \
            .drop('nan_count', axis=1)

In [45]:
df_stats[df_stats['name'] == 'Bruno Silva']

,id,name,nickname,division,record,status,place_of_birth,trains_at,fighting_style,octagon_debut,age,height,weight,reach,leg_reach,wins,losses,draws,wins_by_knockout,first_round_finishes,win_by_dec,win_by_sub,sig_strikes_landed,sig_strikes_attempted,takedowns_landed,takedowns_attempted,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,sig_strikes_defense,takedown_defense,knockdown_avg,fight_time_avg,sig_strikes_standing,sig_strikes_clinch,sig_strikes_ground,head_target,body_target,leg_target
386,387,Bruno Silva,"""Bulldog""",Flyweight Division,15-7-2 (W-L-D),Active,"Piracicaba, Brazil",American Top Team,Grappler,"Sep. 7, 2019",35.0,64.0,125.5,65.0,35.0,15,7,2,6.0,4.0,4.0,5.0,399.0,787.0,2.0,55.0,4.0,5.0,2.3,0.29,52.0,63.0,1.0,10:27,331.0,26.0,42.0,226.0,94.0,79.0

Find missing values

In [46]:
missing_df = pd.DataFrame({
    'missing_count': df_stats.isnull().sum(),
    'missing_precent': round((df_stats.isnull().sum() / len(df_stats)) * 100, 2)
}).sort_values(by='missing_precent', ascending=False)

missing_df

                                 missing_count  missing_precent
first_round_finishes                      2199            70.94
takedowns_landed                          2178            70.26
trains_at                                 2068            66.71
fighting_style                            2046            66.00
wins_by_knockout                          1848            59.61
leg_reach                                 1393            44.94
nickname                                  1257            40.55
reach                                     1111            35.84
takedown_defense                           731            23.58
takedowns_attempted                        583            18.81
sig_strikes_defense                        289             9.32
sig_strikes_landed                         284             9.16
sig_strikes_attempted                      284             9.16
submission_avg                             275             8.87
takedowns_avg                              275             8.87
sig_strikes_absorbed_per_minute            275             8.87
knockdown_avg                              275             8.87
height                                     275             8.87
sig_strikes_landed_per_minute              275             8.87
age                                        257             8.29
place_of_birth                             183             5.90
division                                   111             3.58
weight                                     104             3.35
fight_time_avg                              47             1.52
sig_strikes_ground                          47             1.52
head_target                                 47             1.52
body_target                                 47             1.52
leg_target                                  47             1.52
win_by_dec                                  47             1.52
win_by_sub                                  47             1.52
sig_strikes_standing                        47             1.52
sig_strikes_clinch                          47             1.52
record                                      38             1.23
status                                      28             0.90
name                                         0             0.00
id                                           0             0.00
draws                                        0             0.00
losses                                       0             0.00
octagon_debut                                0             0.00
wins                                         0             0.00

Most of the null values are from new fighters who do not have any stats yet or very old fighters

In [47]:
df_stats[df_stats[['sig_strikes_standing', 'sig_strikes_clinch', 'sig_strikes_ground', 'head_target', 'body_target', 'leg_target']].isnull().all(axis=1)]

,id,name,nickname,division,record,status,place_of_birth,trains_at,fighting_style,octagon_debut,age,height,weight,reach,leg_reach,wins,losses,draws,wins_by_knockout,first_round_finishes,win_by_dec,win_by_sub,sig_strikes_landed,sig_strikes_attempted,takedowns_landed,takedowns_attempted,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,sig_strikes_defense,takedown_defense,knockdown_avg,fight_time_avg,sig_strikes_standing,sig_strikes_clinch,sig_strikes_ground,head_target,body_target,leg_target
50,51,Alberta Cerra,NaN,NaN,NaN,Not Fighting,United States,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,138,Alvaro Ivan Lopez Rodrigues,NaN,NaN,NaN,Not Fighting,Mexico,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,147,Amir Aliakbari,NaN,Heavyweight Division,0-0-0 (W-L-D),Not Fighting,NaN,NaN,NaN,"Jan. 27, 2026",39.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,237,Artem Frolov,NaN,Middleweight Division,0-0-0 (W-L-D),Not Fighting,NaN,NaN,NaN,"Jan. 27, 2026",31.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,249,Asikeerbai Jinensibieke,NaN,NaN,NaN,Active,"Xinjiang, China",NaN,NaN,"Jun. 10, 2022",34.0,NaN,155.0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,302,Bilyal Makhov,NaN,NaN,NaN,Retired,"USSR, Russia",NaN,NaN,"Jan. 27, 2026",35.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
434,435,Carrese Archer,"""One Punch""",NaN,NaN,Not Fighting,NaN,NaN,NaN,"Jan. 27, 2026",33.0,72.0,184.0,73.0,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,487,Chi Lewis-Parry,NaN,Heavyweight Division,0-0-0 (W-L-D),Not Fighting,"Hitchin, United Kingdom",NaN,NaN,"Jan. 27, 2026",39.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552,553,Cody Belisle,"""Bodacious""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",30.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
575,576,Coltin Cole,"""The Truth""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",34.0,NaN,217.0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
584,585,Cory Corbin,"""Hamma""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",36.0,NaN,254.0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,607,Dakota Weigher,"""Iron Slap""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",33.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,611,Dallas Marron,"""El Tigre""",NaN,NaN,Active,NaN,NaN,NaN,"Feb. 9, 2024",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
695,696,Davi Costa,NaN,NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
780,781,Dominik Melendez,"""The Menace""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1593,1594,Ebenezer Braga,NaN,Middleweight Division,0-0-0 (W-L-D),Not Fighting,"Rio de Janeiro, Brazil",NaN,NaN,"Oct. 16, 1998",54.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,889,Enson Inoue,NaN,Lightweight Division,0-0-0 (W-L-D),Not Fighting,United States,NaN,NaN,"May. 30, 1997",56.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
909,910,Evan Sweesy,"""Showtime Swees""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
955,956,Frank Holland,"""The Tank""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",34.0,69.0,250.5,70.0,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
989,990,Garrett Grimes,NaN,NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",29.0,NaN,185.5,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1069,1070,Harrison Garcia,"""Hitman""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1144,1145,Isi Fitikefu,NaN,Light Heavyweight Division,0-0-0 (W-L-D),Not Fighting,New Zealand,NaN,NaN,"Jan. 27, 2026",30.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1153,1154,Issa Isakov,NaN,NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1186,1187,Jair Farias,NaN,NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,1305,Jesse Mariotti,"""Slap Papi""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",26.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1421,1422,Jonathan Correa,"""Puerto Rican Rambo""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1431,1432,Jordan Jackson,"""The Super Saiyan""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",23.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1448,1449,Jorgen Kruth,"""The Last Viking""",Light Heavyweight Division,5-0-0 (W-L-D),Retired,Sweden,NaN,NaN,"Jan. 27, 2026",49.0,74.0,205.0,NaN,NaN,5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1539,1540,Justin Martin,NaN,NaN,NaN,Not Fighting,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1603,1604,Keifer Roberts,"""Keif""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",30.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1627,1628,Kerry Kasik,NaN,NaN,NaN,Not Fighting,United States,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1673,1674,Kitt Campbell,NaN,NaN,NaN,Active,NaN,NaN,NaN,"May. 23, 2025",30.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1773,1774,Logan Greenhalgh,"""Tank""",NaN,NaN,Active,NaN,NaN,NaN,"Jun. 28, 2024",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,1967,Martin Mishtaku,"""Booth""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",36.0,NaN,224.0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2052,2053,Michael Bonnette,"""No Mercy""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",34.0,NaN,170.5,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2063,2064,Michael Smith,"""Slap Jesus""",NaN,NaN,Not Fighting,NaN,NaN,NaN,"Jan. 27, 2026",37.0,71.0,161.5,72.0,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2134,2135,Montrel Talbert,"""Bone""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",30.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2339,2340,Przemyslaw Mysiala,NaN,NaN,NaN,Not Fighting,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2596,2597,Saul Rogers,NaN,NaN,NaN,Not Fighting,United States,NaN,NaN,"Jan. 27, 2026",33.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2614,2615,Sean Mcinerney,"""Poopies""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",36.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2625,2626,Sean Santella,"""Shorty Rock""",Flyweight Division,0-0-0 (W-L-D),Not Fighting,"Dover, United States","Miller Brothers MMA, Nick Catone MMA, Ricardo ...",NaN,"Jan. 27, 2026",38.0,64.0,125.0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2700,2701,Test Fighter2,NaN,NaN,NaN,Retired,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2822,2823,Testy Test,"""Testy""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,34.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2697,2698,Timo Feucht,NaN,Light Heavyweight Division,0-0-0 (W-L-D),Not Fighting,NaN,NaN,NaN,"Jan. 27, 2026",27.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2860,2861,Timothy Thomas,"""The Gorilla""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",34.0,NaN,214.0,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2982,2983,Vineesh Subrahmanyan,"""Vini""",NaN,NaN,Active,NaN,NaN,NaN,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3033,3034,William Marcario,"""Patolino""",NaN,NaN,Not Fighting,Brazil,NaN,NaN,"Jan. 27, 2026",31.0,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

I will merge the two datasets togehter.
But first I will keep only a few features from the stats. Most of the stats are totals, such as wins by knockout, takedowns landed. 
If I use this data there will be data leakage and I will not get the results I want, because the model will already know total stats even of previous fights.

Thtat is why I will keep only the constant values and the averages such as octagon_debut, height, knowckdown_avg.

In [48]:
df_stats = df_stats[['name', 'octagon_debut', 'age', 'height', 'weight', 'reach',
    'leg_reach', 'sig_strikes_landed_per_minute', 'sig_strikes_absorbed_per_minute', 
    'takedowns_avg', 'submission_avg', 'knockdown_avg', 'fight_time_avg']]
df_stats

,name,octagon_debut,age,height,weight,reach,leg_reach,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,knockdown_avg,fight_time_avg
37,AJ Cunningham,"Mar. 2, 2024",30.0,70.0,136.0,71.0,41.0,4.0,6.0,0.00,0.52,0.00,09:34
1882,AJ Dobson,"Feb. 12, 2022",31.0,73.0,185.0,76.0,43.5,4.0,5.0,1.67,0.28,0.28,10:47
1693,AJ Fletcher,"Mar. 12, 2022",26.0,70.0,183.0,67.0,37.0,3.0,5.0,1.54,0.93,0.31,09:43
8,Aalon Cruz,"Jul. 30, 2019",33.0,72.0,155.0,78.0,42.0,8.0,9.0,0.00,0.00,0.85,05:54
0,Aaron Brink,"Nov. 17, 2000",48.0,75.0,231.0,NaN,NaN,3.0,6.0,0.00,0.00,0.00,01:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3097,Zhu Kangjie,"Nov. 23, 2024",29.0,NaN,146.0,NaN,NaN,3.0,1.0,0.33,0.00,0.67,15:00
3098,Zu Anyanwu,"Jul. 11, 2017",41.0,73.0,263.5,77.0,41.0,2.0,2.0,0.65,0.00,0.65,11:32
3102,Zubaira Tukhugov,"Feb. 15, 2014",32.0,68.0,157.5,68.0,38.5,3.0,3.0,2.13,0.00,0.40,12:31
3100,Zviad Lazishvili,"Oct. 23, 2021",31.0,66.0,135.0,69.0,37.0,4.0,6.0,0.00,0.00,0.00,15:00
3103,Zygimantas Ramaska,"Aug. 24, 2024",28.0,71.0,145.5,73.0,NaN,1.0,2.0,0.00,2.41,0.00,06:14

In [49]:
df_stats.isnull().sum()

name                                  0
octagon_debut                         0
age                                 257
height                              275
weight                              104
reach                              1111
leg_reach                          1393
sig_strikes_landed_per_minute       275
sig_strikes_absorbed_per_minute     275
takedowns_avg                       275
submission_avg                      275
knockdown_avg                       275
fight_time_avg                       47
dtype: int64

Weight and Height have some 0 values, this does not make sense as someone can not have a value of height be equal to 0, which will impact the imputation.
I will convert to null and after impute.

In [50]:
df_stats[df_stats['height'] == 0]
df_stats[df_stats['weight'] == 0]

,name,octagon_debut,age,height,weight,reach,leg_reach,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,knockdown_avg,fight_time_avg
28,Adrian Serrano,"Jun. 9, 2000",59.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
36,Adriano Santos,"Oct. 16, 1998",NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
53,Alberto Cerro Leon,"Mar. 11, 1994",NaN,75.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
76,Alex Andrade,"Jun. 9, 2000",49.0,0.0,0.0,NaN,NaN,0.0,3.0,0.00,0.75,0.0,20:00
83,Alex Hunter,"Jul. 27, 1997",NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2564,Valeri Ignatov,"Mar. 5, 1999",NaN,70.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
3008,Wallid Ismail,"Feb. 7, 1997",55.0,70.0,0.0,NaN,NaN,1.0,1.0,1.85,0.46,0.0,16:15
3021,Wes Albritton,"May. 30, 1997",NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
3067,Yoshiki Takahashi,"Feb. 7, 1997",54.0,0.0,0.0,NaN,NaN,2.0,6.0,0.00,2.26,0.0,02:13
767,Yuri Vaulin,"Jul. 27, 1997",NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00

In [51]:
df_stats[['height', 'weight']] = df_stats[['height', 'weight']].replace(0, np.nan)

In [52]:
df_stats.isnull().sum()

name                                  0
octagon_debut                         0
age                                 257
height                              453
weight                              264
reach                              1111
leg_reach                          1393
sig_strikes_landed_per_minute       275
sig_strikes_absorbed_per_minute     275
takedowns_avg                       275
submission_avg                      275
knockdown_avg                       275
fight_time_avg                       47
dtype: int64

In [53]:
df_stats[df_stats['knockdown_avg'].isnull()]

,name,octagon_debut,age,height,weight,reach,leg_reach,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,knockdown_avg,fight_time_avg
2,Abdul Azeem Badakhshi,"Jan. 27, 2026",27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
19,Adam Hunter,"Jan. 27, 2026",39.0,73.0,185.5,73.0,40.0,NaN,NaN,NaN,NaN,NaN,00:00
21,Adam Khaliev,"Jan. 27, 2026",39.0,70.0,170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
25,Adli Edwards,"Jan. 27, 2026",33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
28,Adrian Serrano,"Jun. 9, 2000",59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,William Marcario,"Jan. 27, 2026",31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3035,Willian Souza,"Jan. 27, 2026",36.0,NaN,146.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
3050,Yamato Nishikawa,"Oct. 22, 2022",20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
767,Yuri Vaulin,"Jul. 27, 1997",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00
3094,Zane Frazier,"Nov. 12, 1993",NaN,78.0,230.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00

Fill these stats with 0 because the fighters have just signed with the UFC or are too old fighters.

In [54]:
df_stats[['sig_strikes_landed_per_minute', 'sig_strikes_absorbed_per_minute','takedowns_avg',
        'submission_avg','knockdown_avg']] = df_stats[['sig_strikes_landed_per_minute', 
                                        'sig_strikes_absorbed_per_minute','takedowns_avg','submission_avg',
                                        'knockdown_avg']].fillna(0)

In [55]:
df_stats[df_stats['fight_time_avg'].isnull()].tail(5)

,name,octagon_debut,age,height,weight,reach,leg_reach,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,knockdown_avg,fight_time_avg
2822,Testy Test,"Jan. 27, 2026",NaN,NaN,NaN,NaN,34.0,0.0,0.0,0.0,0.0,0.0,NaN
2697,Timo Feucht,"Jan. 27, 2026",27.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
2860,Timothy Thomas,"Jan. 27, 2026",34.0,NaN,214.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
2982,Vineesh Subrahmanyan,"Jan. 27, 2026",NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN
3033,William Marcario,"Jan. 27, 2026",31.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN

In [56]:
df_stats[['fight_time_avg']] = df_stats[['fight_time_avg']].fillna('00:00')

Converting fight_time_avg to seconds

In [57]:
df_stats['fight_time_avg'] = pd.to_timedelta('00:' + df_stats['fight_time_avg']).dt.total_seconds().astype(int)

In [58]:
df_stats

,name,octagon_debut,age,height,weight,reach,leg_reach,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,knockdown_avg,fight_time_avg
37,AJ Cunningham,"Mar. 2, 2024",30.0,70.0,136.0,71.0,41.0,4.0,6.0,0.00,0.52,0.00,574
1882,AJ Dobson,"Feb. 12, 2022",31.0,73.0,185.0,76.0,43.5,4.0,5.0,1.67,0.28,0.28,647
1693,AJ Fletcher,"Mar. 12, 2022",26.0,70.0,183.0,67.0,37.0,3.0,5.0,1.54,0.93,0.31,583
8,Aalon Cruz,"Jul. 30, 2019",33.0,72.0,155.0,78.0,42.0,8.0,9.0,0.00,0.00,0.85,354
0,Aaron Brink,"Nov. 17, 2000",48.0,75.0,231.0,NaN,NaN,3.0,6.0,0.00,0.00,0.00,111
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3097,Zhu Kangjie,"Nov. 23, 2024",29.0,NaN,146.0,NaN,NaN,3.0,1.0,0.33,0.00,0.67,900
3098,Zu Anyanwu,"Jul. 11, 2017",41.0,73.0,263.5,77.0,41.0,2.0,2.0,0.65,0.00,0.65,692
3102,Zubaira Tukhugov,"Feb. 15, 2014",32.0,68.0,157.5,68.0,38.5,3.0,3.0,2.13,0.00,0.40,751
3100,Zviad Lazishvili,"Oct. 23, 2021",31.0,66.0,135.0,69.0,37.0,4.0,6.0,0.00,0.00,0.00,900
3103,Zygimantas Ramaska,"Aug. 24, 2024",28.0,71.0,145.5,73.0,NaN,1.0,2.0,0.00,2.41,0.00,374

Drop age column because the UFC website does not update it consistently and there are many wrong values especially for older fighters

In [60]:
df_stats.drop(columns='age', inplace=True)

Impute missing values

In [61]:
print(df_stats.columns[df_stats.isnull().any()])
print("\n", len(df_stats.columns[df_stats.isnull().any()]))

Index(['height', 'weight', 'reach', 'leg_reach'], dtype='str')

 4

In [62]:
missing_cols = df_stats.columns[df_stats.isnull().any()]

imputer = KNNImputer(n_neighbors=5)
df_stats[missing_cols] = imputer.fit_transform(df_stats[missing_cols])

# Save as pickle
with open("../models/knn_imputer_stats.pkl", "wb") as f:
    pickle.dump(imputer, f)

In [63]:
df_stats.isnull().sum()

name                               0
octagon_debut                      0
height                             0
weight                             0
reach                              0
leg_reach                          0
sig_strikes_landed_per_minute      0
sig_strikes_absorbed_per_minute    0
takedowns_avg                      0
submission_avg                     0
knockdown_avg                      0
fight_time_avg                     0
dtype: int64

Some names have special characters. When I try and merge the events and stats dataframes these names will not be matched.
I need to normalize those names.

In [64]:
df_stats["name"] = df_stats["name"].map(normalize_name)

In [65]:
df_stats

,name,octagon_debut,height,weight,reach,leg_reach,sig_strikes_landed_per_minute,sig_strikes_absorbed_per_minute,takedowns_avg,submission_avg,knockdown_avg,fight_time_avg
37,aj cunningham,"Mar. 2, 2024",70.0,136.0,71.0,41.0,4.0,6.0,0.00,0.52,0.00,574
1882,aj dobson,"Feb. 12, 2022",73.0,185.0,76.0,43.5,4.0,5.0,1.67,0.28,0.28,647
1693,aj fletcher,"Mar. 12, 2022",70.0,183.0,67.0,37.0,3.0,5.0,1.54,0.93,0.31,583
8,aalon cruz,"Jul. 30, 2019",72.0,155.0,78.0,42.0,8.0,9.0,0.00,0.00,0.85,354
0,aaron brink,"Nov. 17, 2000",75.0,231.0,77.4,43.5,3.0,6.0,0.00,0.00,0.00,111
...,...,...,...,...,...,...,...,...,...,...,...,...
3097,zhu kangjie,"Nov. 23, 2024",67.8,146.0,70.8,39.8,3.0,1.0,0.33,0.00,0.67,900
3098,zu anyanwu,"Jul. 11, 2017",73.0,263.5,77.0,41.0,2.0,2.0,0.65,0.00,0.65,692
3102,zubaira tukhugov,"Feb. 15, 2014",68.0,157.5,68.0,38.5,3.0,3.0,2.13,0.00,0.40,751
3100,zviad lazishvili,"Oct. 23, 2021",66.0,135.0,69.0,37.0,4.0,6.0,0.00,0.00,0.00,900
3103,zygimantas ramaska,"Aug. 24, 2024",71.0,145.5,73.0,40.6,1.0,2.0,0.00,2.41,0.00,374

In [66]:
df_stats.to_csv('../data/notebooks/stats_cleaned.csv', index = False)